name: hyper_launcher
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  bot_toast: ^4.1.3
  flutter:
    sdk: flutter
  hotkey_manager: ^0.2.3
  preference_list: ^0.0.2
  process_run: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
